[package]
name = "dlrs"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "3.1.18"
regex = "1.5.6"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.18.5", features = ["full"] }
serde_json = "1.0"
futures = "0.3"
colored = "2.0.0"
